# permissions for end users to view nificas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifica-viewer-role
rules:
- apiGroups:
  - nifitoolkit.safaricom.et
  resources:
  - nificas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifitoolkit.safaricom.et
  resources:
  - nificas/status
  verbs:
  - get
